version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=bdvidj
      - RUNNING_IN_DOCKER=true
      - APP_ADDRESS=Promo.qform.app:8080
    expose:
      - "8080"

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bdvidj
    expose:
      - "5432"
volumes:
  pgdata: